const CHANGE_CATOGORY = 'artists/CHANGE_CATEGORY';
const CHANGE_ALPHA = 'artists/CHANGE_ALPHA';
const CHANGE_ARTIST_LIST = 'artists/CHANGE_ARTIST_LIST';
const CHANGE_PAGE_COUNT = 'artists/PAGE_COUNT';
const CHANGE_ENTER_LOADING = 'artists/ENTER_LOADING';
const CHANGE_PULLUP_LOADING = 'artists/PULLUP_LOADING';
const CHANGE_PULLDOWN_LOADING = 'artists/PULLDOWN_LOADING';
const CHANGE_MORE = 'artists/MORE'

export {
    CHANGE_CATOGORY,
    CHANGE_ALPHA,
    CHANGE_ARTIST_LIST,
    CHANGE_PAGE_COUNT,
    CHANGE_ENTER_LOADING,
    CHANGE_PULLUP_LOADING,
    CHANGE_PULLDOWN_LOADING,
    CHANGE_MORE
}
